version: '3.5'

services:

  rabbitmq:
    image: rabbitmq:3.8.4-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - env/rabbitmq.env
    networks:
      - rabbitmq_network_static_resource_demo

  mongodb:
    image: mongo:4.2.7
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    expose:
      - 27017
    env_file:
      - env/mongodb.env
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongodb_network_static_resource_demo

  mongo_express:
    image: mongo-express:0.54.0
    container_name: mongo_express
    restart: always
    depends_on:
      - mongodb
    env_file:
      - env/mongo_express.env
    ports:
      - 8081:8081
    networks:
      - mongodb_network_static_resource_demo

  log_reader:
    image: log_reader:0.5.0
    build:
      context: ../../logreader
      dockerfile: Dockerfile
    container_name: log_reader
    restart: always
    depends_on:
      - mongodb
    env_file:
      - env/components_mongodb.env
    ports:
      - 8080:8080
    networks:
      - mongodb_network_static_resource_demo

  log_writer:
    image: log_writer:0.5.0
    build:
      context: ../../logwriter
      dockerfile: Dockerfile-log-writer
    container_name: log_writer
    restart: "no"
    depends_on:
      - mongodb
      - rabbitmq
    env_file:
      - env/components_common.env
      - env/components_mongodb.env
      - env/components_rabbitmq.env
    environment:
      - SIMULATION_LOG_FILE=logs/logfile_log_writer.log
    volumes:
      - simulation_logs:/logs
    networks:
      - mongodb_network_static_resource_demo
      - rabbitmq_network_static_resource_demo

  simulation_manager:
    image: simulation_manager:0.5.0
    build:
      context: ../../simulation-manager
      dockerfile: Dockerfile-manager
    container_name: manager
    restart: "no"
    depends_on:
      - rabbitmq
      - log_writer
    env_file:
      - env/components_common.env
      - env/components_rabbitmq.env
      - env/manager.env
    volumes:
      - simulation_logs:/logs
    networks:
      - rabbitmq_network_static_resource_demo

  resource_forecaster:
    image: resource_forecaster:0.1.0
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: resource_forecaster
    restart: "no"
    depends_on:
      - rabbitmq
    env_file:
      - env/components_common.env
      - env/components_rabbitmq.env
      - env/resource.env
    environment:
      - SIMULATION_COMPONENT_NAME=resource_forecaster
      - SIMULATION_LOG_FILE=logs/logfile_resource_forecaster.log
      - RESOURCE_TYPE=ResourceForecaster
      - RESOURCE_TYPES=Load,Generator
      - RESOURCE_FORECAST_COMPONENT_IDS=load1,generator1
      - RESOURCE_FORECAST_STATE_CSV_FOLDER=./
      - FORECAST_HORIZON=PT36H
    volumes:
      - simulation_logs:/logs
      - ./load1.csv:/load1.csv
      - ./generator1.csv:/generator1.csv
    networks:
      - rabbitmq_network_static_resource_demo

volumes:
  mongodb_data:
    name: mongodb_data_static_resource_demo
  simulation_logs:
    name: simulation_logs_static_resource_demo

networks:
  rabbitmq_network_static_resource_demo:
    name: rabbitmq_network_static_resource_demo
  mongodb_network_static_resource_demo:
    name: mongodb_network_static_resource_demo
